sentinel/home/models.py
""" models used by the sentinel application """

from sentinel import db
from sentinel.utils import xmltojson

class Report(db.Document):
    """ a report document """
    OWASPZAPReport = db.DynamicField()

    def insert(self, json_report):
        """ inserts the report to the database """
        self.OWASPZAPReport= json_report['OWASPZAPReport']
        self.save()

    def __repr__(self):
        return "<Report %r at %r >" % (self.OWASPZAPReport['site']['@name'], self.OWASPZAPReport['@generated'])

sentinel/home/forms.py
from flask.ext.wtf import Form

# Import Form elements
from wtforms import SelectField, StringField

class ScanlistForm(Form):
    """
    Form to give a list of dates on which scans are performed for a given site.
    """
    date = SelectField('scans')
    site = StringField('site')

sentinel/home/controllers.py
""" home controllers """

# Flask imports
from flask import Blueprint, render_template, request,\
                  redirect, url_for, session, jsonify, flash, abort
from flask.ext.login import login_user , logout_user , current_user , login_required

# Import the database object from the main app module
from sentinel import db, app

# Import models
from .models import Report

# Import forms
from sentinel.home.forms import ScanlistForm

# Import utility functions
from sentinel.utils.extract_info import risk_histo, uri_histo, top_of_hist,\
     frequency_of_alerts
from sentinel.utils.auth import get_user
from sentinel.utils.home import fetch_report, fetch_scan_dates, fetch_alert_list

# Create blueprint
home = Blueprint('home', __name__)


# ************ROUTES**************************************#
@home.route('/sites', methods=['GET', 'POST'])
@login_required
def homepage():
    """
    The homepage controller checks if the given 'username' is in the session.
    If the user is in the session, the homepage is shown, else, it shows an
    'unauthorised' message.
    """
    if not current_user:
        abort(404)

    if current_user.isAdmin:
        return redirect(url_for("admin.admin_home"))

    return render_template("home/sites.html", user=current_user)


@home.route('/sites/<site_index>', methods=['GET', 'POST'])
@login_required
def scanlist(site_index):
    """
    POST request:
    The page shows a list of dates on which scans are performed for a particular
    site. If there were no scan performed, it shows that as a message to the user.
    """
    try:
        site = current_user.ownedSites[int(site_index)]
    except:
        return abort(404)

    dates = fetch_scan_dates(site)

    if len(dates) > 0:
        form = ScanlistForm()
        form.date.choices = dates
        return render_template("home/scanlist.html", site=site, form=form)

    flash("No scans performed yet for this site.", "error")
    return redirect(url_for("home.homepage"))


@home.route('/getSummaryData', methods=['POST'])
@login_required
def get_summary_data():
    """
    Returns a json with the data required to generate the summary.
    """
    form = ScanlistForm()
    report = fetch_report(form.site.data, form.date.data)
    report_data = report.OWASPZAPReport
    report_id = str(report.id)
    risk_hist = risk_histo(report_data)
    alerts = frequency_of_alerts(report_data)
    top10_uris = top_of_hist(uri_histo(report_data), 10)
    context = {'risk_levels': risk_hist, 'alerts': alerts, 'top10_uris':top10_uris, 'report_id': report_id}
    return jsonify(context)


@home.route('/full_report/<report_id>', methods=['GET', 'POST'])
@login_required
def get_full_report(report_id):
    report = fetch_alert_list(report_id)
    return render_template("home/full-report.html", report=report)

sentinel/templates/home/full-report.html
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">

<!-- Latest compiled and minified JavaScript -->
<link rel="stylesheet" href="{{ url_for('static', filename='js/bootstrap.min.js')}}">

</head>

<body>
<h2>ZAP Version : {{ report['@version'] }}</h2>
Report generated on : {{ report['@generated'] }}<br>
<table class="table table-bordered">
    <tr>
        <th>Host</th>
        <td>{{ report.site['@host'] }}</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>{{ report.site['@name'] }}</td>
    </tr>
    <tr>
        <th>Port</th>
        <td>{{ report.site['@port'] }}</td>
    </tr>
</table>

<h2>ALERTS</h2>
{% for alert in report.site.alerts.alertitem %}
<h3>{{ alert.alert }}</h3>
<table class="table table-bordered table-hover">
    <tr>
        <th>Confidence</th>
        <td>{{ alert.confidence }}</td>
    </tr>
    <tr>
        <th>Count</th>
        <td>{{ alert.count }}</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ alert.desc }}</td>
    </tr>
    <tr>
        <th>PluginID</th>
        <td>{{ alert.pluginid }}</td>
    </tr>
    <tr>
        <th>Reference</th>
        <td>{{ alert.reference }}</td>
    </tr>
    <tr>
        <th>Risk Code</th>
        <td>{{ alert.riskcode }}</td>
    </tr>
    <tr>
        <th>Risk Description</th>
        <td>{{ alert.riskdesc }}</td>
    </tr>
    <tr>
        <th>Solution</th>
        <td>{{ alert.solution }}</td>
    </tr>
    <tr>
        <th>WascID</th>
        <td>{{ alert.wascid }}</td>
    </tr>
    <tr>
        <th>Instances</th>
        <td>
            {% for instance in alert.instances.instance %}
            <ul class="list-group">
                {% for key, val in instance.iteritems() %}
                <li class="list-group-item"><span style="font-weight: bold;">{{ key }}</span> : {{ val }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </td>
    </tr>
</table>
{% endfor %}



</body>
</html>

sentinel/templates/home/scanlist.html
{% extends "layout.html" %}
{% block content %}
<style>
#date{ width:100%;}
</style>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 main_cont">
                <!--<a href="{{url_for('home.homepage', username=session['username'])}}">Home</a>-->
<h3> {{site}} </h3>
<!--<select>
    {% for date in dates %}
       <option value="{{ date }}">{{ date }}</option>
    {% endfor %}
</select>-->
<div class="col-md-4 ">
<div class="site_box">
<form action="" method="post" name="selectscan">

		 <label for="site">Site:</label>
          {{ form.site(value=site, class="form-control input-box")  }}<br>
   
         <label for="date"> Please select the scan:</label>
         {{ form.date (class="form-control input-box") }}<br>
    
   <input type="button" value="GO" class="btn btn-primary" onclick="showGraphs()">
	
</form>
</div>
</div>
<div class="col-md-8">
<div class="site_box">
<a href="#" id="fullreportlink" target="_blank" class="btn btn-info" style="visibility: hidden">View full report</a>
<div id="risklevels" style="width: 550px; margin: 0 auto"></div>
<div id="alerttypes" style="width: 550px; margin: 0 auto"></div>
<div id="vulnerableuris" style="width: 550px; margin: 0 auto"></div>
</div>
</div>
            </div>
        </div>
    </div>


<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript" src="http://code.highcharts.com/highcharts-more.js"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/summaryGraphs.js')}}"></script>
{% endblock %}

sentinel/templates/home/sites.html
{% extends "layout.html" %}
{% block content %}
<div class="container ">
    <div class="row">
	<div class="col-lg-12 ">
            {% with flash_msgs = get_flashed_messages(category_filter=["error", "message"]) %}
                {% if flash_msgs %}
                    {% for msgs in flash_msgs %}
					<div class="alert alert-info mar_t">
					  <strong> {{ msgs }}</strong>
					</div>
                       
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
	
        <div class="col-lg-12 main_cont">
            <h3> My Sites </h3>
			<div class="site_table">
            <table class="table table-striped ">
                <thead>
                    <th>#</th>
                    <th>Site</th>
                </thead>
                <tbody>
                    {% for site in user.ownedSites %}
                        <tr>
                            <td>{{loop.index}}</td>
                            <td><a href={{url_for('home.scanlist', site_index=loop.index0)}}>{{site}}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
			</div>
		</div>
		<div class="col-lg-12 main_cont">
            {% if current_user.isAdmin %}
		    <h3>Add Site </h3>
			<div class="add_site">
			<div class="col-md-12">
            <form method="POST" action="#" accept-charset="UTF-8" role="form">
			<div class="col-md-9">
                {{ form.csrf_token }}
                {{ form.url(class_='form-control input-box', placeholder='Site URL', required=true) }}
				
			</div>
			<div class="col-md-3">			
              <button class="btn btn-primary" type="submit" name="add">Add</button>
			 </div> 
            </form>
            {% endif %}
			</div>
        </div>
    </div>
</div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/datatables.js')}}"></script>
<script type="text/javascript">
    $(function() {
        $('.table').DataTable();
    });
</script>
{% endblock %}